# Generated by Django 6.0.4 on 2026-05-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricaldata',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='electricaldata',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
